-- MySQL Script generated by MySQL Workbench
-- Mon Feb  1 10:28:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema cookingbookdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS cookingbookdb;
CREATE SCHEMA cookingbookdb DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cookingbookdb;
-- -----------------------------------------------------
-- Table TRezepte
-- -----------------------------------------------------
DROP TABLE IF EXISTS TRezepte;
CREATE TABLE TRezepte (
    RezID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    RezName VARCHAR(35) NOT NULL,
    RezInstru LONGTEXT NULL,
    PRIMARY KEY (RezID),
    UNIQUE INDEX RezID_UNIQUE (RezID ASC)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table TEinheiten
-- -----------------------------------------------------
DROP TABLE IF EXISTS TEinheiten;
CREATE TABLE TEinheiten (
    EinKuerz CHAR(5) NOT NULL,
    EinName VARCHAR(35) NOT NULL,
    PRIMARY KEY (EinKuerz)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table TKategorien
-- -----------------------------------------------------
DROP TABLE IF EXISTS TKategorien;
CREATE TABLE TKategorien (
    KatKuerz CHAR(5) NOT NULL,
    KatName VARCHAR(35) NOT NULL,
    PRIMARY KEY (KatKuerz)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table TZutaten
-- -----------------------------------------------------
DROP TABLE IF EXISTS TZutaten;
CREATE TABLE TZutaten (
    ZutID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ZutName VARCHAR(35) NULL,
    PRIMARY KEY (ZutID)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table TListen
-- -----------------------------------------------------
DROP TABLE IF EXISTS TListen;
CREATE TABLE TListen (
    LisID INT NOT NULL AUTO_INCREMENT,
    LisName VARCHAR(35) NULL,
    LisDesc VARCHAR(35) NULL,
    PRIMARY KEY (LisID)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table TRezeptListen
-- -----------------------------------------------------
DROP TABLE IF EXISTS TRezeptListen;
CREATE TABLE TRezeptListen (
    RezID INT UNSIGNED NULL,
    LisID INT NULL,
    PRIMARY KEY (RezID, LisID),
    INDEX fk_LisID1_idx (LisID ASC),
    INDEX fk_RezID2_idx (RezID ASC),
    CONSTRAINT fk_RezID2 FOREIGN KEY (RezID) REFERENCES TRezepte (RezID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT fk_LisID1 FOREIGN KEY (LisID) REFERENCES TListen (LisID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table TRezeptKategorien
-- -----------------------------------------------------
DROP TABLE IF EXISTS TRezeptKategorien;
CREATE TABLE TRezeptKategorien (
    RezID INT UNSIGNED NULL,
    KatKuerz CHAR(5) NULL,
    PRIMARY KEY (RezID, KatKuerz),
    INDEX fk_KatKuerz1_idx (KatKuerz ASC),
    INDEX fk_RezID3_idx (RezID ASC),
    CONSTRAINT fk_RezID3 FOREIGN KEY (RezID) REFERENCES TRezepte (RezID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT fk_KatKuerz1 FOREIGN KEY (KatKuerz) REFERENCES TKategorien (KatKuerz) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table TRezeptZutaten
-- -----------------------------------------------------
DROP TABLE IF EXISTS TRezeptZutaten;
CREATE TABLE TRezeptZutaten (
    RezID INT UNSIGNED NOT NULL,
    ZutID INT UNSIGNED NOT NULL,
    EinKuerz CHAR(5) NOT NULL,
    ZutMenge INT UNSIGNED NULL,
    PRIMARY KEY (RezID, ZutID),
    INDEX fk_ZutID1_idx (ZutID ASC),
    INDEX fk_RezID4_idx (RezID ASC),
    INDEX fk_EinKuerz1_idx (EinKuerz ASC),
    CONSTRAINT fk_RezID4 FOREIGN KEY (RezID) REFERENCES TRezepte (RezID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT fk_ZutID1 FOREIGN KEY (ZutID) REFERENCES TZutaten (ZutID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT fk_EinKuerz1 FOREIGN KEY (EinKuerz) REFERENCES TEinheiten (EinKuerz) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Data for table TRezepte
-- -----------------------------------------------------
START TRANSACTION;
USE cookingbookdb;
INSERT INTO TRezepte (RezID, RezName, RezInstru)
VALUES (1, 'Sushi', NULL);
COMMIT;
-- -----------------------------------------------------
-- Data for table TEinheiten
-- -----------------------------------------------------
START TRANSACTION;
USE cookingbookdb;
INSERT INTO TEinheiten (EinKuerz, EinName)
VALUES ('g', 'gram');
INSERT INTO TEinheiten (EinKuerz, EinName)
VALUES ('mg', 'miligram');
INSERT INTO TEinheiten (EinKuerz, EinName)
VALUES ('l', 'liter');
INSERT INTO TEinheiten (EinKuerz, EinName)
VALUES ('ml', 'mililiter');
INSERT INTO TEinheiten (EinKuerz, EinName)
VALUES ('kg', 'kilogram');
INSERT INTO TEinheiten (EinKuerz, EinName)
VALUES ('tbsp', 'tablespoon');
INSERT INTO TEinheiten (EinKuerz, EinName)
VALUES ('tsp', 'teaspoon');
INSERT INTO TEinheiten (EinKuerz, EinName)
VALUES ('psc', 'piece');
COMMIT;
-- -----------------------------------------------------
-- Data for table TZutaten
-- -----------------------------------------------------
START TRANSACTION;
USE cookingbookdb;
INSERT INTO TZutaten (ZutID, ZutName)
VALUES (1, 'Sushi-Reis');
INSERT INTO TZutaten (ZutID, ZutName)
VALUES (2, 'Salmon');
INSERT INTO TZutaten (ZutID, ZutName)
VALUES (3, 'Nori');
INSERT INTO TZutaten (ZutID, ZutName)
VALUES (4, 'Salt');
COMMIT;
-- -----------------------------------------------------
-- Data for table TListen
-- -----------------------------------------------------
START TRANSACTION;
USE cookingbookdb;
INSERT INTO TListen (LisID, LisName, LisDesc)
VALUES (1, 'Japanese', NULL);
COMMIT;
-- -----------------------------------------------------
-- Data for table TRezeptListen
-- -----------------------------------------------------
START TRANSACTION;
USE cookingbookdb;
INSERT INTO TRezeptListen (RezID, LisID)
VALUES (1, 1);
COMMIT;
-- -----------------------------------------------------
-- Data for table TRezeptZutaten
-- -----------------------------------------------------
START TRANSACTION;
USE cookingbookdb;
INSERT INTO TRezeptZutaten (RezID, ZutID, EinKuerz, ZutMenge)
VALUES (1, 1, 'g', 250);
INSERT INTO TRezeptZutaten (RezID, ZutID, EinKuerz, ZutMenge)
VALUES (1, 2, 'g', 150);
INSERT INTO TRezeptZutaten (RezID, ZutID, EinKuerz, ZutMenge)
VALUES (1, 3, 'psc', 1);
INSERT INTO TRezeptZutaten (RezID, ZutID, EinKuerz, ZutMenge)
VALUES (1, 4, 'tsp', 1);
COMMIT;